spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  batch:
    jdbc:
      initialize-schema: always

    job:
      name: ${job.name:NONE}
      enabled: false


logging:
  level:
    root: info
    com:
      srpinfotec:
        cvslog:
          batch:
            RevisionLogFileToDB: Debug

server:
  port: 80
