spring:
  application:
    name: cvslog

  jackson:
    property-naming-strategy: SNAKE_CASE

  config:
    import:
      - classpath:/application-cvs.yml
      - classpath:/application-testdb.yml

logging:
  level:
    root: info
