spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  batch:
    jdbc:
      initialize-schema: never

    job:
      enabled: false
      name: ${job.name=NONE}

logging:
  level:
    root: info

server:
  port: ${SERVERPORT}

management:
  endpoints:
    web:
      exposure:
        include: prometheus