spring:
  application:
    name: api

  profiles:
    active: local
    include:
      - core

  jackson:
    property-naming-strategy: SNAKE_CASE

---
spring.config.activate.on-profile: local
server:
  port: 8081

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: prometheus

---
spring.config.activate.on-profile: prod
server:
  port: ${CL_API_SERVER_PORT}

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: prometheus