spring:
  application:
    name: domain

---
spring.config.activate.on-profile: local
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/cvslog
    username: root
    password: 1416
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 300
        show_sql: true
        format_sql: true

---
spring.config.activate.on-profile: prod
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${CL_DB_URL}
    username: ${CL_DB_USERNAME}
    password: ${CL_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 300
        show_sql: false
        format_sql: false